name: example
description: A new Flutter project.

Author: Ketan Choyal <ketanchoyal@gmail.com>
homepage: https://github.com/ketanchoyal/

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_search_widget:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
