name: mapbox_search_widget
description: This package provides some helper widgets to use with mapbox_search library.
version: 1.0.0+1
homepage: https://github.com/ketanchoyal/mapbox_search_widget

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mapbox_search: ^3.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
